In [35]:
# 1 Solve the following system of linear equations using cramer's rule
def determinantOfMatrix(mat):
 
    ans = (mat[0][0] * (mat[1][1] * mat[2][2] -
                        mat[2][1] * mat[1][2]) -
           mat[0][1] * (mat[1][0] * mat[2][2] -
                        mat[1][2] * mat[2][0]) +
           mat[0][2] * (mat[1][0] * mat[2][1] -
                        mat[1][1] * mat[2][0]))
    return ans
 
# This function finds the solution of system of
# linear equations using cramer's rule
def findSolution(coeff):
 
    # Matrix d using coeff as given in
    # cramer's rule
    d = [[coeff[0][0], coeff[0][1], coeff[0][2]],
         [coeff[1][0], coeff[1][1], coeff[1][2]],
         [coeff[2][0], coeff[2][1], coeff[2][2]]]
     
    # Matrix d1 using coeff as given in
    # cramer's rule
    d1 = [[coeff[0][3], coeff[0][1], coeff[0][2]],
          [coeff[1][3], coeff[1][1], coeff[1][2]],
          [coeff[2][3], coeff[2][1], coeff[2][2]]]
     
    # Matrix d2 using coeff as given in
    # cramer's rule
    d2 = [[coeff[0][0], coeff[0][3], coeff[0][2]],
          [coeff[1][0], coeff[1][3], coeff[1][2]],
          [coeff[2][0], coeff[2][3], coeff[2][2]]]
     
    # Matrix d3 using coeff as given in
    # cramer's rule
    d3 = [[coeff[0][0], coeff[0][1], coeff[0][3]],
          [coeff[1][0], coeff[1][1], coeff[1][3]],
          [coeff[2][0], coeff[2][1], coeff[2][3]]]
 
    # Calculating Determinant of Matrices
    # d, d1, d2, d3
    D = determinantOfMatrix(d)
    D1 = determinantOfMatrix(d1)
    D2 = determinantOfMatrix(d2)
    D3 = determinantOfMatrix(d3)
     
    print("D is : ", D)
    print("D1 is : ", D1)
    print("D2 is : ", D2)
    print("D3 is : ", D3)
 
    # Case 1
    if (D != 0):
       
        # Coeff have a unique solution.
        # Apply Cramer's Rule
        x = D1 / D
        y = D2 / D
         
        # calculating z using cramer's rule
        z = D3 / D 
         
        print("Value of x is : ", x)
        print("Value of y is : ", y)
        print("Value of z is : ", z)
 # Case 2
    else:
        if (D1 == 0 and D2 == 0 and
            D3 == 0):
            print("Infinite solutions")
        elif (D1 != 0 or D2 != 0 or
              D3 != 0):
            print("No solutions")
            # Driver Code
if __name__ == "__main__":
 
    # storing coefficients of linear
    # equations in coeff matrix
    coeff = [[2, -1, 1, -3],
             [1, 1, -3, 17],
             [5, -2, -4, 20]]
 
    findSolution(coeff)

D is :  -16
D1 is :  -32
D2 is :  -48
D3 is :  64
Value of x is :  2.0
Value of y is :  3.0
Value of z is :  -4.0


In [2]:
import numpy as np
A = np.array([[1, 0, 0, 0], [3, 2, 0, 0], [0, 1, -1, 0], [-2, 3, 1, 3]])
b = np.array([2, 4, -1, -4])
x = np.linalg.solve(A, b)
x



array([ 2., -1., -0.,  1.])

The solution of s.o.e. by CR is:
[2, -3, 4, 1, 6]


In [2]:
M=np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
m,n=M.shape
if m==n:
    print('Matrix is square')
else:
    print('Matrix is not square')

Maatrix is square


In [16]:
M3=np.array([[2,-2,4],[-1,2,-4],[1,-2,-3]])
M4=np.linalg.matrix_power(M3,2)
if (M4==M3.T).all():
    print("matrix is not idempotent.")
else:
    print('matrix is idempotent.')

matrix is idempotent.


In [18]:
np.linalg.det(M)

0.0

In [29]:
A=np.array([[1,0,0],[0,-1,0],[0,0,-1]])
A
if np.linalg.det(A)!=0:
    if (np.linalg.inv(A)==A.T).all():
        print("Matrix is orthogonal")
    else :
        print("Matrix is not orthogonal")

Matrix is orthogonal


In [22]:
Ev=np.linalg.eigvals(A)
Ev
if np.all(Ev>0):
    print('POsitive Def')
elif np.all(Ev>=0):
    print('POsitive semi Def')
elif np.all(Ev<0):
    print('Negative Def')
elif np.all(Ev<=0):
    print('Negative semi Def')

In [16]:
import numpy as np
A=np.array([[2,-1,1],[1,1,-3],[5,-2,-4]])
A
B=np.array([-3,17,20])
B
row,col=A.shape
x=[0]*col
for i in range(col):
    temp=A.copy()
    temp[:,i]=B
    x[i]=np.linalg.det(temp)/np.linalg.det(A)
    x

In [19]:
P=np.array([[4,1,3,1],[1,4,1,3],[3,1,4,1],[1,3,1,4]])
P
c=np.linalg.eigvals(P)
c


array([9., 1., 5., 1.])